### PR TITLE
Opensees

### PR DESCRIPTION
**Pull request by ebrahimraeyat**
- [x] writing node loads
- [x] writing static solver options
- [x] writing pvd recorder for VTK output compatible
- [x] writing Fix Nodes Boundary Conditons

### CODE REVIEW

**Comment by ebrahimraeyat** [comment]
I rebased FreeCAD master repo, but it seems that it did not apply to it!!! i am very confused. I will try to learn more about git!

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=8&t=44285&start=10#p379247
 
If we would like to work together the Version 1, means we both do merge the commits from the other, none of us should do a rebase. Than the merge works great. As soon as one of us does a rebase merging is not the way to go. We would use the Verion 2 or 3 of the post above.

Try what I have suggested in this post https://forum.freecadweb.org/viewtopic.php?f=8&t=44285&start=20#p380503 and the post before. 

cheers bernd

**Comment by berndhahnebach** [comment]
I will base my femopenseesebrahim on your development branch.  Just tell me which is your branch on which you do develop? myopensees or opensees?

**Comment by berndhahnebach** [comment]
If you make a PR:
the last commit before your first new commit should have the same id than the last commit of the branch you are makeing the PR to.
Thus tell me your dev branch.

**Comment by ebrahimraeyat** [comment]
thanks @berndhahnebach, I will continue to plan 1. thus i don't rebase at all.

**Comment by berndhahnebach** [comment]
I will close this PR. You can ask any question here https://forum.freecadweb.org/viewtopic.php?f=8&t=44285

Make as much PRs you would like to.

**Pull request closed without merging**
