### PR TITLE
Fembodyconstraint

### PR DESCRIPTION
**Pull request by qingfengxia**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
will have a look at the body constraint after release of FreeCAD 0.18

cheers bernd

**Comment by berndhahnebach** [comment]
have another few days patience qing feng. I will have a look at the PR when I am finished with the material stuff I am on ATM.

cheers Bernd

**Comment by qingfengxia** [comment]
Hi Bernd,

I recently change my job to be a senior research software engineer, moving away from experimental work for the time being.

if you have some important email, you can directly email me

qingfeng.xia@ukaea.uk.

Thx

Qingfeng
________________________________

**Comment by berndhahnebach** [comment]
find the reason why this is not yet merged here:  https://forum.freecadweb.org/viewtopic.php?f=18&t=43092

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?t=33124

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/FreeCAD_bhb/commits/fembodyconstraint

**Comment by qingfengxia** [comment]
great let me know if anything I should do



Sent from my Mi phone
Feb 20, 2020 04:40 wrote on Bernd Hahnebach <notifications@github.com>:

https://github.com/berndhahnebach/FreeCAD_bhb/commits/fembodyconstraint

**Comment by berndhahnebach** [comment]
see https://forum.freecadweb.org/viewtopic.php?f=18&t=33124&start=10#p370448

**Pull request closed without merging**
