### PR TITLE
typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/945/commits/cfaa2c031252e

inclued in https://github.com/FreeCAD/FreeCAD/pull/945

FYI: the real 945 is branch https://github.com/berndhahnebach/FreeCAD_bhb/commits/bhbnewsolver it has history rewritten ...

**Comment by berndhahnebach** [comment]
In FEM we do not have tabs. From time to time I use 

`grep -rl --exclude=\*.{qm,fcstd,png} $'\t' ./src/Mod/Fem/
`

to find them. How about to include this in travis? We could start with FEM source directory and extend it to other source directories which are cleaned from tabs? I do not have a glue how to add such command to travis and let travis fail if it returns some output.

bernd

**Comment by luzpaz** [comment]
Yes, it's a good idea. Feel free to mention that in https://freecadweb.org/tracker/view.php?id=3206

**Comment by berndhahnebach** [comment]
BTW:

in your various commits lately you added white spaces to FEM code. It's a good idea to remove them before commiting changes, not only in FEM and Python. On python you could use flake8 command to check for trailing white spaces. I have removed them. 

bernd

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/FreeCAD_bhb/commit/1245c2cf37906bcdfe555f68c7a973865bf21154

**Pull request closed without merging**
