### PR TITLE
FEM: import/export YAML/JSON mesh (squashed)

### PR DESCRIPTION
**Pull request by joha2**
Squashed commits for FEM import/export YAML/JSON mesh. (see PR https://github.com/berndhahnebach/FreeCAD_bhb/pull/53)

---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
the commit date is 19th of April ... we have June 8th ...

git rebase -i HEAD~2

before the last commit, the one you would like to change the date put an e for edit, close the editor. Rebaseing will stop at the commit  to edit, than change the date with

git commit --amend --date="now"

git rebase --continue

**Comment by berndhahnebach** [comment]
et voila date is set to totay just a few seconds before this post ... 

https://github.com/FreeCAD/FreeCAD/commit/d78f5a1151ae4a6709e3e6c114a0cafb2a205da7

**Comment by joha2** [comment]
Hey thanks for merging @berndhahnebach! Now that you've already merged the PR, is correcting the date still an issue? I think it is not bad if the date of the commit is from April since review needs its time.

**Comment by berndhahnebach** [comment]
I changed the date the way described ... IMHO it is better to have not merged a commit into FreeCAD master which date it month old ...

**Pull request closed without merging**
