### PR TITLE
FEM: opensees, completed static analysis process

### PR DESCRIPTION
**Pull request by ebrahimraeyat**
- [x] writing node loads
- [x] writing static solver options
- [x] writing pvd recorder for VTK output compatible
- [x] writing Fix Nodes Boundary Conditons

### CODE REVIEW

**Comment by berndhahnebach** [comment]
merged

**Comment by berndhahnebach** [comment]
I did two commits as well. Give the merge a try yourself ...

**Comment by berndhahnebach** [comment]
I made a PR to your repo ... :-)

**Comment by ebrahimraeyat** [comment]
Thanks bernd. i merged it. then run:
`git pull origin opensees`

to get your commit in my local. thanks

**Pull request merged**
