### PR TITLE
FEM: typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
+ some whitespace formatting 
(Hey @berndhahnebach hope these fixes are more useful than annoying. Should I submit this to another branch btw?)

### CODE REVIEW

**Comment by berndhahnebach** [comment]
I like well written code. All FEM Python is flake8 compatible. C++ should neither have any white space nor tabs. I really apretiate them. Since rebasing such changes could be difficault is some cases I'd be happy if you make the PR here on my repo an not directly to the FreeCAD master. 

Best to use this branch: https://github.com/berndhahnebach/FreeCAD_bhb/tree/femdev

keep up your good detective work on issue tracker and in the regard of these typos. 

cheers bernd

BTW: I still have in mind we need to change the GMSH TaskPanel but first the GSoC elmer stuff needs to be finished.

**Comment by berndhahnebach** [comment]
Added to https://github.com/FreeCAD/FreeCAD/pull/1018

**Comment by luzpaz** [comment]
FYI, i wanted to make a PR to femdev branch but it was behind master. in the future should I still make a PR there if that's the case ?

**Comment by berndhahnebach** [comment]
Better to use femdev. I only commit to femdev if I'm sure I will make a PR with this commits. My master is updated any time I fetch FreeCAD master. Since ATM most of my development is taking place in femnewsolver it happened femdev is a bit behind. 

bernd

**Comment by luzpaz** [comment]
:+1:

**Comment by luzpaz** [comment]
@berndhahnebach do you mind rebasing your femdev branch ? I have a few more trivial fixes when you're ready. Thanks!

**Comment by berndhahnebach** [comment]
done

**Pull request closed without merging**
