### PR TITLE
FEM: femtools/femutils.py typos and whitespace fixes

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell`

### CODE REVIEW

**Review by luzpaz — COMMENTED** [review]
https://github.com/berndhahnebach/FreeCAD_bhb/pull/42/files#diff-9abf467bad561aa19050d2ff33338da3R30 
is this line superfluous ?

**Comment by berndhahnebach** [comment]
no, see for example https://github.com/FreeCAD/FreeCAD/blob/fe2660b4684b51100ccc19c7479d08f7ae507398/src/Mod/Fem/femtools/femutils.py#L125

I have been using FreeCAD in all my development. Markus who initially wrote the module prefered to import FreeCAD as App. I did not wanted to change th whole module.

**Comment by berndhahnebach** [comment]
merged

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1625

**Pull request closed without merging**
