### PR TITLE
Fem C++ source documentation (Analysis & Contraint) 

### PR DESCRIPTION
**Pull request by ceeli**
A little source documentation for the C++ part of the Fem module. I also removed a few unnecessary overrides who didn't do anything different from the base class implementation.

### CODE REVIEW

**Comment by ceeli** [comment]
The rest of the C++ changes I did during GSoC are have not worked out the way I hoped, I'm going to make a post in the forum soon. I'm soon going to make another pull request for the python changes which will be much bigger.

**Comment by berndhahnebach** [comment]
mhh I merged by accident in my branch and overwrote the branch. I can not reopen the PR. ...

**Comment by berndhahnebach** [comment]
rebases on master :-) https://github.com/berndhahnebach/FreeCAD_bhb/commits/gsoccppdoc

I will have a look soon.

**Comment by berndhahnebach** [comment]
merged
https://github.com/FreeCAD/FreeCAD/commits/88637aeb202b481a16cbd82c8767a0cc2745cfe1

**Comment by ceeli** [comment]
Nice, thanks :)

**Pull request merged**
