### PR TITLE
Fem: import/export mesh as yaml/json

### PR DESCRIPTION
**Pull request by joha2**
This feature branch adds support for simple exchange of small meshes via JSON and YAML exchange formats. Implementation is quite easy and makes excessive use of the make_mesh function. Still missing: Reimport of exported groups. At the moment they are just ignored. This PR refers to https://forum.freecadweb.org/viewtopic.php?f=18&t=35480

---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
have a few days patience johannes. I will have a look at the PR when I am finished with the material stuff I am on ATM.

cheers Bernd

**Comment by joha2** [comment]
Yeah @berndhahnebach , take the time you need! No stress intended!

Best wishes
Johannes

**Comment by berndhahnebach** [comment]
to give it a try I rebased it on master https://github.com/berndhahnebach/FreeCAD_bhb/commits/femyaml

**Comment by berndhahnebach** [comment]
offtopic: Johannes ... 

would it be possible to split between App and Gui in https://github.com/FreeCAD/FreeCAD/blob/d2d8a30cb2c600b4fc2983df0c156e8416aa328a/src/Mod/Fem/feminout/importFenicsMesh.py

see post on forum: https://forum.freecadweb.org/viewtopic.php?f=10&t=35884&start=120#p309077 and how Gui should be guarded: https://forum.freecadweb.org/viewtopic.php?f=10&t=35884&start=120#p308909

we may open a new topic on FEM, just up to you 

cheers bernd

**Comment by joha2** [comment]
Hey @berndhahnebach thanks for your reply! I've added a topic to the developers section in the forum on that https://forum.freecadweb.org/viewtopic.php?f=10&t=36560

I think in the next few days I will perform just a check with FreeCAD.GuiUp and think about a long term solution.

Best wishes
Johannes

**Comment by berndhahnebach** [comment]
I changed more than I did expected before ... Would you check if it still works ...

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/FreeCAD_bhb/commits/femyaml

**Comment by berndhahnebach** [comment]
what do you thick johannes, should we use an own file extension? I will merge my python mesh exporter, importer too. There I have the same problem. We could use .femyl and fempy or .fym and .fpy instead of .yml and .py This would things much simpler to know it us a fem mesh inside the file.

cheers bernd

BTW: started to write a unit test for your yaml mesh exporter

**Comment by berndhahnebach** [comment]
I adapted all changes I made from z88 mesh exporte which.I restructured as well. See commuts before your commits.

cheers bernd

**Comment by joha2** [comment]
Hey @berndhahnebach thanks for your comments. I will check the functionality in more detail later. On a first sight, your changes look promising: I am also a friend of more splitting into sub problems and to seperate the read and write functions from document and object creation. Therefore good work! I also have the feeling that changing the file extensions could provide a better picture to which subsystem the files belong to. So I think it is a good idea to go to femyaml, femjson, fempy instead of the pure endings (as long as we provide some comment somewhere that these are only yaml, json and Python files).

Best wishes
Johannes

**Comment by berndhahnebach** [comment]
Hey Johannes, @joha2 

great ... BTW: I finished the unti test as well. I will wait until you give some feed back, but no hurry ... I will regularly rebase the branch on master since this is automated on my local machine.

What would you prefere long or short file extension means either femyaml or fym (fyl, fsn) as well as fempy or fpy (Python mesh export)

cheers bernd

**Comment by joha2** [comment]
Hey @berndhahnebach "schoenen Maennertag" :-)

I would prefer long endings since the times of three-letter-endings are long over and I think "fempy, femjson, femyaml" are far more clear than "fpy" (ok) or "fsn" or "fyl". Maybe we could also think of (since its only the mesh structure) of "meshpy, meshjson, meshyaml".

BTW: Thanks for also guarding the FreeCADGui import. :-)

**Comment by joha2** [comment]
Hey @berndhahnebach how can I get your changes onto this branch? Or should I just fork from your FC and commit directly on the femyaml branch? I observed there are still some problems which I wanted to repair.

**Comment by joha2** [comment]
~Ok I found the problem: The call of write in line 94 does not match the calling convention defined in lines 182 to 185. I would prefer the filename in the first position, then the mesh, but this is up to you.~

~I would furthermore suggest to move the convert_femmesh_to_dict method to the importFemTools module such that they both build a pair: make_femmesh and convert_femmesh_to_dict (they are doing opposite things).~ Maybe one can unify the names further. 

Another nice thing would be (since gmsh supports it) to integrate pyr5 and pyr13 elements, independently of whether calculix uses them. 

With these measures we have two functions which provide an easy-to-use interface to the FemMesh structure and which only need a special dictionary which should simplify the integration of new formats further. (If desired both of these functions could be converted to C++ to improve speed.) I think this is also a useful step towards working with a pre-deformed geometry in the FEM toolbox.

**Comment by berndhahnebach** [comment]
> 
> 
> Hey @berndhahnebach how can I get your changes onto this branch? Or should I just fork from your FC and commit directly on the femyaml branch? I observed there are still some problems which I wanted to repair.

you do not need to fork my repo. Take your FC repo and add my FC repo a remote repo wie git remote add ...  Than you can merge or rebase my changes in your branch, or check out my branch and create a new one for you. or cherry-pick the commits from my branch in your branch or whatever. Afterwards you just make a PR with your branch to my femyaml branch. There are lots of workflows ... Let's go for the following!

I will stop rebasing femyaml. On your FC repo you do a:
```
git remote add bernd https://github.com/berndhahnebach/FreeCAD_bhb
git fetch bernd
git branch -a
# all my branches will be there
git checkout remote/bernd/femyaml
git chekcout -b whatEverNameYouLikeFemyaml
# do your dev commit
# push to your repo
# give an informating here

```
```
# than I will do some development give feedback here
# than you do
git  fetch bernd
git checkout  whatEverNameYouLikeFemyaml
# merge all my changes into your branch
git merge remote/bernd/femyaml

```
Ss long as noone does a rebase merging will work in any case without a error. This is what git is made for, distributed development.

cheers bernd

**Comment by berndhahnebach** [comment]
about all other changes you proposed, go for it and give feedback if they are implemented.
cheers bernd

**Comment by joha2** [comment]
hey @berndhahnebach I corrected the errors and did some other stuff in https://github.com/joha2/FreeCAD/tree/femyaml-improve (new branch, derived from your femyaml branch) What now?

Best wishes
Johannes

**Comment by berndhahnebach** [comment]
I merged yours in my femyaml branch. I will have a look and report back ... 

https://github.com/berndhahnebach/FreeCAD_bhb/commits/femyaml

Bernd

**Comment by berndhahnebach** [comment]
some small changes. ... https://github.com/berndhahnebach/FreeCAD_bhb/commits/femyaml
If you are happy and if it did not break something I would go for a merge into master?

bernd

**Comment by berndhahnebach** [comment]
How about squasing all commits into one which you are the author of before merging into master ? This would give a clean history for this small addition.

bernd

**Comment by joha2** [comment]
Hey @berndhahnebach thanks for merging and checking! Yes we can go into master and I would also be happy if you could squash the commits into one. (How does this work?) I tested the code by merging your changes into my femyaml-improved branch and compiling FreeCAD again. There were no errors occuring for importing and exporting meshes as json and yaml.

Best wishes
Johannes

**Comment by berndhahnebach** [comment]
give the dquash a try ... 

check out a new branch to be sure if something goes wrong:
git checkout -b femyamlsquashed

git rebase -i HEAD~10

an interactive vi will open

pick or p before commit will mean the commit is used as it is. If you remove a line the commit is deleted. If you exchange the pick with squash or simple s the commit is squashed in the commit before. Ok search the first commit leave the pick, on all later commits exchange the pick with the s. Save the file git will make the rebase. Check if all went well. git log -10 oneline and git diff yourfemyamlbranch. The log should only show one commit for your yaml dev and the diff should give no difference. Ahh and than rebase on FreeCAD master and make a new PR to mey femdev.

bernd

**Comment by joha2** [comment]
OK thank you very much for the great help! It all worked like expected. I squashed the commits into one and rebased on master. Now I will make a pull request to femdev.

Best regards
Johannes

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/commit/d78f5a1151ae4a6709e3e6c114a0cafb2a205da7

**Pull request closed without merging**
