### PR TITLE
typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@berndhahnebach ping

**Comment by berndhahnebach** [comment]
patience ...

**Comment by berndhahnebach** [comment]
:-)

**Comment by luzpaz** [comment]
wasn't sure you saw it 😆

**Comment by berndhahnebach** [comment]
have some more patience ... As soon as I will continue on this beam stuff I merge this ... Bernd

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1166

since you made it on fembeam branch I thought there where only typos for this new branch. Since develpment at the moment has stoped at fembeams I thought it can wait.

All femrelated stuff is best to make a pr on femdev branch.

**Pull request closed without merging**
