### PR TITLE
FEM: FemMesh: AddGroup and AddGroupElements functions exposed to Python

### PR DESCRIPTION
**Pull request by joha2**
By merging this PR the FemMesh object gets three new functions

* addGroup(name_string, type_string, [group_id])
* addGroupElements(group_id, elements_ids_list)
* removeGroup(group_id)

`type_string` can assume values "All", "Node", "Edge", "Face", "Volume", "0DElement", "Ball".

These functions have to be tested and the code needs a review by a C++ expert. 

The `addGroup` function takes the group_id from the underlying Salome framework, so group ids are not reliable when they are restored after serialization. ~I am not sure whether one could force a special id.~ It seems possible to force a specific id, but the Salome framework in FreeCAD seems to ignore the argument to `AddGroup`.

The `addGroupElements` function is the counter part to the `getGroupElements` function. It gets a list as second argument because I wanted a mutable type to be used, whereas the tuple return type from `getGroupElements` is ok. Further it filters for elements of a certain type (the one for the group) and inserts them only if they are compatible and not already in the group.

The `removeGroup` function deletes a group with given id, returning True or False depending on whether deletion was successful.

Of course all three functions are low-level and therefore do not influence the GUI. Therefore directly after creation of the new groups with elements, there is no new group element in the mesh in the object tree of the document. Maybe this has to be taken care of by using a special method in FemMeshGmsh and its FemMeshNetgen counterpart object.

---
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0` (Except 3x RuntimeError: No SWIG wrapped library loaded)
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
damn time is running fast ...
Do you know what the Ball and0D groups are?

**Comment by berndhahnebach** [comment]
IMHO we shoud move the C++ implementation into code file FemMesh.cpp

With this we could call them from C++ too. In FemMeshPyImp.cpp we would just call the method from FemMesh.cpp.

How does that souds?

**Comment by berndhahnebach** [comment]
Do you have some tast data ready? If we have small test examples we could just make a unit test from it. 

Usually if the unit test is not just implemented with the methods it takes ages to implement them ;-)

cheers bernd

**Comment by berndhahnebach** [comment]
Do we have a forum topic or should we continue to disscuss here. In the forum the disscussion will be kept for the future. Here it will be lost some how.

**Comment by joha2** [comment]
Hey @berndhahnebach,
Nice to hear from you. Are you deeply drowned in real life? :D 
For the forum discussion I would suggest to revive

https://forum.freecadweb.org/viewtopic.php?f=18&t=35778

Best regards and see you there :-)
Johannes

**Comment by berndhahnebach** [comment]
merged

**Pull request closed without merging**
