### PR TITLE
FEM: Fenics import/export corrections

### PR DESCRIPTION
**Pull request by joha2**
* fixed make_femmesh call due to renaming in the FEM module

### CODE REVIEW

**Comment by joha2** [comment]
I didn't know how to remove the other commits from my branch, since they are the difference between the actual master and your master which is some commits behind. I hope this is no problem. :-(

**Comment by berndhahnebach** [comment]
not at all

**Comment by berndhahnebach** [comment]
your email is correct too :-)

**Comment by berndhahnebach** [comment]
merged

**Comment by berndhahnebach** [comment]
commits entfernen kannst sehr einfsch mit git rebase

**Pull request closed without merging**
