### PR TITLE
FEM: Fenics mesh import/export: removed lxml dependency

### PR DESCRIPTION
**Pull request by joha2**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master` (unfortunately also merged :-( )
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0` (AssertionError: Couldn't load TestPathApp)
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [X] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists
- [X] flake8

And please remember to update the Wiki with the features added or changed once this PR once it is merged.

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
FYI 
your branch is not fully clean rebased on master, thus all the conmits show up. It does not matter for me I can cherry-pick your commit.

bernd

**Comment by joha2** [comment]
Yeah I did a 'git pull upstream master'. Is there a possibility to afterwards rebase on master?

**Comment by berndhahnebach** [comment]
Sorry Johannes for the noise, it was my femdev branch which was not rebased on FreeCAD/master 

Autsch :-)

**Comment by joha2** [comment]
Hehe. No problem! :-)
The Travis CI job has exceeded time limit again. Is there anything we could do about that?

**Comment by berndhahnebach** [comment]
some people including FreeCAD master have exceeded time limit on travis. They stopped to give any more time limit to FreeCAD devs. I have been asking twice already. The crux is I need more resources on travis as I would use if they would give me more time limit. ATM any of my pulls runs out of time limit. If they would give me more time limit only one of ten jobs would even reach this time limit. Anyway we need to be biiiiiiiig as big as the linux kernel, haha. They would as give as much time we need. business ... 

cheers bernd

**Pull request closed without merging**
