### PR TITLE
FEM: typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
@berndhahnebach please examine 5e90601 when you get a chance to see if it's a correct fix. Thanks!

**Comment by luzpaz** [comment]
@berndhahnebach when you get a moment, please acknowledge

**Comment by berndhahnebach** [comment]
merged ... sorry for the delay. I have been off for a few days. Bernd

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1431

**Pull request closed without merging**
