### PR TITLE
Fem: Fenics: xdmf groups improvements and interface classes for Fenics

### PR DESCRIPTION
**Pull request by joha2**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [X] Branch rebased on latest master `git pull --rebase upstream master`
- [X] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [X] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [X] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.

---

### CODE REVIEW

**Comment by berndhahnebach** [comment]
I squashed your changes of import export in one commit. Are you fine with this Johannes? 

https://github.com/berndhahnebach/FreeCAD_bhb/commit/522cb4bc1 If yes I would go for PR for upcomming 0.17 immediately.

**Comment by joha2** [comment]
Hey  bernd! I'm perfectly fine with that. Best regards Johannes

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1277

I do not close the PR, because the fenics tools is not included in my PR.

**Comment by joha2** [comment]
Why's that? :-(

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/FreeCAD_bhb/commit/a4dde2b8fd47825a3e6e338424670f7c29bea44e

It does not do anything, or does it do?

**Comment by joha2** [comment]
Ah, the fenics tools provides interface classes for easy usage of fenics based on an xdmf type mesh. So it is in fact very useful as a step towards an fc fenics interface, though it's not perfect, anyway. br johannes

**Comment by berndhahnebach** [comment]
ok, I will include it in my next PR Bernd

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/pull/1302

**Pull request closed without merging**
