### PR TITLE
FEM typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Sorry if I submit to the wrong branch. I was trying to ascertain which was your PR branch...?

**Comment by berndhahnebach** [comment]
merged on femdev branch 

https://github.com/berndhahnebach/FreeCAD_bhb/commits/femdev

BTW: how do you test on all these typos?

**Comment by berndhahnebach** [comment]
reopened it to get informed if you gone answer ...

**Comment by luzpaz** [comment]
I run `codespell.py -d -q 3 --skip="*.po,*.ts" | grep -i "Fem"`

**Comment by luzpaz** [comment]
I just ignored 
```
./src/Mod/Fem/FemGmshTools.py:272: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:273: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:275: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:276: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:279: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:282: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:283: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:284: eles  ==> else
./src/Mod/Fem/FemGmshTools.py:286: eles  ==> else
```
Location in source: https://github.com/berndhahnebach/FreeCAD_bhb/blob/master/src/Mod/Fem/FemGmshTools.py#L272-L287

Though strategically it may be beneficial to rename this variable because it looks like a misstype of `else` a commonly used word. It could be 'whitelisted' and therefore not throw false-positives but since it's a commonly used word...if we could rename it I think it would be more ideal. Of course this is super low-priority and trivial.

**Comment by berndhahnebach** [comment]
thanks for the hint, it's not a problem to rename it. Since I'm dedicated to code formating I will rename it ...

**Comment by berndhahnebach** [comment]
https://github.com/berndhahnebach/FreeCAD_bhb/commit/16336e26a32c87ab9873d9fa3164ab63563dd24c?diff=split

**Comment by luzpaz** [comment]
you rock 🥇

**Pull request closed without merging**
