### PR TITLE
FEM: Fenics xml xdmf refactor

### PR DESCRIPTION
**Pull request by joha2**
Refactoring and clean up of Fenics XML, XDMF import/export code.
Flake8 compliant. Can export to XDMF now (Paraview readable):
* tet4, tet10
* tri3, tri6
* edge2, edge3

Still TODO: XDMF import non-operational, XDMF export to HDF5 for very large meshes,
mesh functions

### CODE REVIEW

**Comment by joha2** [comment]
I don't know why the Travis CI call fails :-(

The job exceeded the maximum time limit for jobs, and has been terminated.

Sounds strange.

**Comment by berndhahnebach** [comment]
> I don't know why the Travis CI call fails :-(
The job exceeded the maximum time limit for jobs, and has been terminated.
Sounds strange.

The FreeCAD main repo has no time limit. I have had contact a to travis a few times but they do not give me more time :-(

**Comment by berndhahnebach** [comment]
I'm gone integrate it if GSoC proposal time has finished ...

**Comment by joha2** [comment]
Okeydokey

**Comment by berndhahnebach** [comment]
merged in my femdev: https://github.com/berndhahnebach/FreeCAD_bhb/tree/femdev

do you have some example to test with?

**Comment by berndhahnebach** [comment]
hi johannes,

I had a look at your modules. The import, insert, and export methods are all implemented in importFenicsMesh.py. In all your other modules there are just the reading and writing methods. Since these modules do not implement any import or export I would not name the modules export... or import... BTW Why do you used all this modules? Why not just copy all defs in the module importFenicsMesh.py ?

bernd

**Comment by joha2** [comment]
Hi bernd! Thanks for merging! Yeah you're right, I will rename them. The split up into the four files had the charme that the helper functions needed are not all in one file and I don't have to search through a file which has 1000 lines to find them. Also refactoring some of the inner structure could be done more easily.

Example: You could test it with every non-hex mesh from gmsh or netgen. Just export them and import the result into paraview.

**Comment by joha2** [comment]
Somehow the actual code of femdev is outdated. I renamed the files due to your suggestions: Is that ok? The conflicts between my PR and the actual code of the femdev branch seem to come from the merging of my last PR, which is strange because the time stamp says it is from 2 days ago. Is there anything to be done by me to fix that? Best wishes Johannes

**Comment by berndhahnebach** [comment]
Sorry Johannes for not answering so long. I have been of  a few days. In the regard of your renaming. Have a look at this module:  https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Fem/FemMeshTools.py Imagine we would use an own module for every def. We would have a mess in the Fem directory ...

My suggestion for your importer / exporter would be one of these two module names schema:
import and export in one module:
importFenicsXML.py --> all import and export of Fenics xml
importFenicsXDMF.py --> all import and export of Fenics xmdf

import and export in separate modules:
importFenicsXML.py --> import of Fenics xml
importFenicsXDMF.py --> import  of Fenics xmdf
exportFenicsXML.py -->  export of Fenics xml
exportFenicsXDMF.py --> export  of Fenics xmdf

I'm myself am not 100% sure which is better (51 to 49 for import and export in one module ... ). At the moment in FreeCAD workbenches both systems are used. FEM at the moment uses the first one only (import an export in one module named importXXXX)

What do you think of this? 

cheers bernd

**Comment by joha2** [comment]
Hey bernd, no problem! Was the GSoC proposal successful? :-)
My intention with the many files was that the Fenics mesh import and export are very different and I also did not want to have massive code doubling in some cases. I have the feeling that since the import and export of meshes is a more or less complicated task (in contrast to e.g. the point cloud one), it would be useful to put import/export modules in their own sub directory (to not mess up the Fem main directory) and there put it into a file name scheme like the one you suggested:

   helpersFormat.py # helper functions for mesh sub structures if needed for Format
   readFormat.py # reading format converting into meshdata structure
   writeFormat.py # writing format from meshdata structure
   importFormat.py # import/export coupling to FreeCAD like your Z88 template

This is also useful because most of the formats, I have seen in the FC code need a more or less complicated pre/post processing to give adequate meshdata or adequate import/export file format.
Also a ordering like this could be useful for beginners in the FC code, who just want to contribute some format import/export without diving too much into the Fem Workbench itself.

In the concrete case of XML/XDMF it is useful because the formats are somehow similar but also in some cases very different. Also the code files in particular for XDMF exceeded 200 lines of code quickly. And to just not mess them both up, for me it was convenient to split them. 

Best wishes Johannes

**Comment by berndhahnebach** [comment]
Sometime in python scripting one needs to access the read and write defs of a file format. I would assume for any format these defs are in import or export module of this format.

In the regard of a subdirectory: The modules would be a bit cumbersome to import at the moment, but this may changes in the future. 

I still think we should go for one of the two suggested name structures. 

What do you think? Bernd

bernd

**Comment by joha2** [comment]
OK, then I would prefer the solution with import/export in different files. Because as I mentioned you have more files in your directory, but the code is maybe smaller and better manageable. What about helper functions which are used in both files? Is it suitable to put them into your FemTools file?

**Comment by berndhahnebach** [comment]
> What about helper functions which are used in both files? Is it suitable to put them into your FemTools file?

Depends ... If they are useful for other file formats too, I would put them in importToolsFem.py module. If they are not useful for other file formats I would put them in the import module.

**Comment by joha2** [comment]
So the export module then depends on the import module? This seems a bit counter intuitive for me. Why not the other way around? Sorry for discussing this issue that long, but I only want to play the advocatus diaboli a bit since maybe later we have to perform a large refactoring if there are more import/export formats implemented by several authors, I think.

**Comment by berndhahnebach** [comment]
> Sorry for discussing this issue that long, but I only want to play the advocatus diaboli a bit since maybe later we have to perform a large refactoring if there are more import/export formats implemented by several authors, I think.

Your are welcome. As long as we get it finished and get it into master the way we are happy with the code it is worth discussing. If you gone start splitting import and export we need refactoring the z88 and vtk anyway. They include import and export in the import module. But the more I think about the more I would split them into import and export.

> So the export module then depends on the import module? This seems a bit counter intuitive for me. Why not the other way around?

At the moment all import and export is in the import modules in FEM. That is why I would first look for in the import module if I'm searching. I don't mind if you put it in the export module. Why would you put them in the export?

bernd

**Comment by joha2** [comment]
To the last point: This was just an example, that the other variant is also possible. But, e.g. for Fenics the import is very hard to implement and it is not clear if it is useful to reimport meshes from Fenics, while the the export is more or less straightforward. Anyway: does it matter if we "mess up" the Fem directory by import/export/helper files for different formats? As long as people see which .py files to which part of Fem belong this should not matter?

Best wishes
Johannes

**Comment by berndhahnebach** [comment]
we had a mess in Fem directory until Junuary this year. Dozens of file and very cumbersome to find what you look for. I spent some time to sort all this out. Just check an old commit from december 2016.

**Comment by berndhahnebach** [comment]
https://github.com/FreeCAD/FreeCAD/tree/4360c0b8b3182f6356bc45d55984af9863d0b971/src/Mod/Fem

**Comment by berndhahnebach** [comment]
Merged your code. Johannes, do you have some files to test the import with? Some which where not exported by FreeCAD.
Bernd

**Comment by joha2** [comment]
Hey bernd! Thanks for merging!
At least there are some XML test files here
https://people.sc.fsu.edu/~jburkardt/data/xml/xml.html

One or two of them don't work since they seem to be created by hand and are not compatible with XML description provided in the Fenics source code itself. In the next few days, I will also generate some files with fenics to be reimported into FreeCAD and provide them here.

For XDMF there is no import, yet. The export could be tested by generating a mesh in FreeCAD, exporting it as XDMF and opening it in paraview.

Best wishes
Johannes

**Comment by joha2** [comment]
These five meshes are generated with the mesh generator of fenics and saved as XML files. They are tested with my import code.

[testmeshes_xml_import.zip](https://github.com/berndhahnebach/FreeCAD_bhb/files/984249/testmeshes_xml_import.zip)

**Comment by joha2** [comment]
Since you merged this pull request, I will close it. For the next feature, I will create a new one.
Best regards
Johannes

**Comment by berndhahnebach** [comment]
PR to master made. Sorry Johannes it has takes quite long (about 4 weeks) this time. 

BTW: I made some changes on the FEM unit system. It is simpler to add new unit tests now. We may should think to add some or at least one for each Fenics mesh type too?

bernd

**Comment by joha2** [comment]
Yes you're absolutely right! Unittests may consist of: generating a mesh with Fenics import in FreeCAD, check mesh data for correctness. And for the export: generate simple geometry, export mesh and check outcome of XML and XDMF files respectively.

**Pull request closed without merging**
